## Write instrument specific instrument file functions by changing the Configuration{<:<MYINSTRUMENT>} section 
function write_instrument_files(directory::AbstractString,design::DataFrame,source::Vector{<:Labware},target::Vector{<:Labware},config::Configuration,slotting::SlottingDict=slotting_greedy(vcat(source,target),config);kwargs...) 

  tt = transfer_table(design,source,target)

  CSV.write(joinpath(directory,"transfer_table.csv"),tt)

  return nothing 


end


"""
    compile(
        directory::AbstractString,
        pourcast::Pourcast;
        packing_method::Function = packing_greedy,
        kwargs...
    ) -> Nothing

Compile a `Pourcast` into one or more protocol folders on disk.

For each configuration in `configs(pourcast)`, this function determines which
source/target labware pairs must be simultaneously accessible (“slotted”) and
uses `packing_method` to produce one or more feasible slotting layouts. For each
layout, it extracts the corresponding well-to-well transfer submatrix for that
configuration and writes instrument files into a protocol-specific subfolder.

# Output layout

For each configuration `c`, files are written under:

`directory/<config_type>/<protocol_name>/...`

where `<config_type> = string(get_config_type(configs(pourcast)[c]))` and
`<protocol_name>` is generated by `random_adverb_verb_pairs`.

# Arguments
- `directory::AbstractString`: Root directory where configuration/protocol
  subdirectories will be created.
- `pourcast::Pourcast`: The plan to compile (provides labware, configurations,
  and flows).

# Keyword Arguments
- `packing_method::Function = packing_greedy`: Packing/slotting routine called as
  `packing_method(slotting_pairs, config)`. It must return a collection of
  slotting dictionaries (one per generated protocol).
- `check_quality::Bool = true`: Force the compiler to check the quality of solution before compiling using the `solution_quality` function.  
- `kwargs...`: Forwarded keyword arguments passed to `slotting_requirements(...)`
  and `write_instrument_files(...)` (e.g., a transfer threshold).


# Side Effects
- Creates directories using `mkdir` when needed.
- Writes instrument/protocol files via `write_instrument_files`.

# Algorithm (per configuration)
1. Compute `slotting_reqs = slotting_requirements(pourcast; kwargs...)`.
2. Convert `slotting_reqs[c]` into a vector of `(source::Labware, target::Labware)`
   pairs that require co-slotting.
3. Generate one or more slotting solutions:
   `slotting_dicts = packing_method(slotting_pairs, configs(pourcast)[c])`.
4. For each solution `p`:
   - Determine slotted sources/targets from the dict keys.
   - Convert labware to well-index selectors using `labware_indices(pourcast)`.
   - Slice the configuration transfer matrix:
     `protocol_design = transfers_by_config(pourcast)[c][s_idxs, t_idxs]`.
   - Convert `protocol_design` to a `DataFrame` and write files.
"""
function compile(directory::AbstractString,pourcast::Pourcast; packing_method::Function = packing_greedy, kwargs...)
    if !isdir(directory)
        mkdir(directory) 
    end 
    pc = pourcast_to_json(pourcast)
    JSON.json(joinpath(directory,"pourcast.json"),pc)

    sources = source_labware(pourcast)
    targets = target_labware(pourcast)

    plt_image_dir = joinpath(directory,"target_plate_images") 

    if !isdir(plt_image_dir)
        mkdir(plt_image_dir)
    end 

    for target in targets 
        p = plot(target)
        plot_well_heatmap!(p,target)
        savefig(p,joinpath(plt_image_dir,"$(JLIMS.name(target)).png"))
    end 

    
    C = length(configs(pourcast))


    slotting_reqs = slotting_requirements(pourcast)
    trfs_by_config = transfers_by_config(pourcast)


    for c in 1:C 
        slotting_pairs = Tuple{Labware,Labware}[]

        for i in eachindex(sources)
            for j in eachindex(targets)
                if slotting_reqs[c][i,j]
                    push!(slotting_pairs,(sources[i],targets[j]))
                end 
            end
        end 
        if length(slotting_pairs)== 0 
            continue
        end


        config_directory = joinpath(directory,string(nameof(get_config_type(configs(pourcast)[c]))))
        if !isdir(config_directory)
            mkdir(config_directory)
        end


        slotting_dicts = packing_method(slotting_pairs,configs(pourcast)[c])
        n_protocols = length(slotting_dicts)
        protocol_names=random_adverb_verb_pairs(n_protocols)

        for p in 1:n_protocols
            slotted_labware=collect(keys(slotting_dicts[p]))
            protocol_sources = filter(x-> in(x,sources),slotted_labware)
            protocol_targets = filter(x-> in(x,targets),slotted_labware)

            src_idx_dict, tgt_idx_dict = labware_indices(pourcast)
            s_idxs = vcat(map(x->src_idx_dict[x],protocol_sources)...)
            t_idxs = vcat(map(x->tgt_idx_dict[x],protocol_targets)...)

            protocol_design = trfs_by_config[c][s_idxs,t_idxs] # get all transfers for this configuration with the labware that are currently slotted 
        
            protocol_design = DataFrame(protocol_design,:auto)
            protocol_directory = joinpath(config_directory,protocol_names[p])
            if !isdir(protocol_directory)
                mkdir(protocol_directory)
            end 
            write_instrument_files(protocol_directory,protocol_design,protocol_sources,protocol_targets,configs(pourcast)[c],slotting_dicts[p];kwargs...)
            plt = plot_slotting(configs(pourcast)[c].deck,slotting_dicts[p];kwargs...)
            savefig(plt,joinpath(protocol_directory,"loading_instructions.png"))
            loading_df = slottingdict_to_df(slotting_dicts[p])
            CSV.write(joinpath(protocol_directory,"loading_table.csv"),loading_df)


        end 

    end 
    return nothing 
end 


